# Generated by Django 4.0.6 on 2022-07-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_author_followers_alter_author_following_and_more'),
        ('post', '0002_article_update_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.author', verbose_name='author_articles'),
        ),
    ]
