# Generated by Django 4.0.6 on 2022-07-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_author_remove_user_followers'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_tags',
            field=models.ManyToManyField(related_name='user_selected_tags', to='post.tags'),
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(to='common.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(to='common.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
