# Generated by Django 4.0.6 on 2022-07-25 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_selected_tags_author_followers_author_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to='common.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, to='common.author'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
