# Generated by Django 4.0.6 on 2022-07-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
                ('price_from', models.IntegerField(default=0)),
                ('price_to', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Standart', 'Standart'), ('Premium', 'Premium'), ('Urgent', 'Urgent')], max_length=4096)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhunt.category')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhunt.employer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhunt.location')),
            ],
        ),
    ]
